# Generated by Django 5.0.14 on 2026-05-23 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('minute', models.CharField(blank=True, help_text="e.g. 45', HT, FT", max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.league')),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='OddsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('home_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('draw_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('away_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('over_2_5_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('under_2_5_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('btts_yes_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('btts_no_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_snapshots', to='matches.match')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='matches.league')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_date', 'league', 'status'], name='matches_mat_match_d_fb2f14_idx'),
        ),
    ]
