# Generated by Django 5.0.14 on 2026-05-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='minute',
            field=models.CharField(blank=True, help_text="e.g. 45', HT, FT", max_length=10, null=True),
        ),
    ]
