# Generated by Django 5.0.14 on 2026-05-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=100)),
                ('cache_hits', models.IntegerField(default=0)),
                ('cache_misses', models.IntegerField(default=0)),
                ('hit_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelAccuracyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('total_predictions', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('accuracy_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
