# Generated by Django 5.0.14 on 2026-05-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_type', models.CharField(choices=[('SAFE', 'Safe Bet'), ('VALUE', 'Value Bet'), ('ACCA', 'Accumulator')], default='SAFE', max_length=20)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence_score', models.IntegerField(help_text='0-100 scale')),
                ('description', models.TextField()),
                ('is_vip_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betting_tips', to='matches.match')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['tip_type', 'is_vip_only'], name='betting_bet_tip_typ_763bc0_idx')],
            },
        ),
    ]
