# Generated by Django 6.0.5 on 2026-05-29 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        ('matches', '0002_alter_match_minute'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void'), ('CASHOUT', 'Cashed Out')], default='SUBMITTED', max_length=20)),
                ('slip_type', models.CharField(choices=[('SINGLE', 'Single'), ('ACCUMULATOR', 'Accumulator')], default='SINGLE', max_length=20)),
                ('total_stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_odds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('potential_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('is_cashed_out', models.BooleanField(default=False)),
                ('cash_out_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_slip', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('HOME_WIN', 'Home Win (1)'), ('DRAW', 'Draw (X)'), ('AWAY_WIN', 'Away Win (2)'), ('OVER_2_5', 'Over 2.5'), ('UNDER_2_5', 'Under 2.5'), ('BTTS_YES', 'BTTS Yes'), ('BTTS_NO', 'BTTS No')], max_length=20)),
                ('odds_at_placement', models.DecimalField(decimal_places=2, max_digits=6)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_selections', to='matches.match')),
                ('bet_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.betslip')),
            ],
        ),
        migrations.AddIndex(
            model_name='betslip',
            index=models.Index(fields=['user', 'status'], name='betting_bet_user_id_e6faaf_idx'),
        ),
    ]
