# Generated by Django 6.0.5 on 2026-05-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_type',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank Transfer')], default='BANK', max_length=20),
        ),
    ]
