# Generated by Django 5.0.14 on 2026-06-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_withdrawalrequest_payout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BET_STAKE', 'Bet Stake'), ('BET_WIN', 'Bet Winnings'), ('BET_REFUND', 'Bet Refund'), ('CASHOUT', 'Cash Out'), ('BONUS', 'Bonus'), ('COMMISSION', 'Commission')], max_length=20),
        ),
    ]
