# Generated by Django 5.0.14 on 2026-05-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('MATCH_START', 'Match Start'), ('GOAL', 'Goal Scored'), ('TIP_ALERT', 'High Confidence Tip')], default='TIP_ALERT', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
